projeto/config/routes.rb
Rails.application.routes.draw do
  resources :alunos
  resources :users

  root :to => "home#index"

end

projeto/app/models/aluno.rb
class Aluno < ActiveRecord::Base
	
	def nome_completo
		"#{nome} - #{ra}"
	end

end

projeto/app/models/user.rb
class User < ActiveRecord::Base
	validates_presence_of :nome ,:password

	validates_confirmation_of :password
	validates_length_of :password, :minumum => 6, :allow_blank => false

	validates :email,	:presence => true,
						#:format => {:with => /\A[^@]+@[^@\.]+\z/ },
						:uniqueness => true
	#has_secure_password
end

projeto/app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno was successfully created.' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno was successfully updated.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:ra, :nome, :curso)
    end
end

projeto/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

projeto/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@alunos = Aluno.limit(3)
	end

	
end

projeto/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def index
		render :new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to @user, :notice => 'Cadastro criado com sucesso!'
		else 
			render :new
		end

	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to @user, :notice => 'Dados Atualizados com sucesso'
		else
			render :update
		end
	end	


	def user_params
		params.require(:user).permit(:nome, :email, :password, :password_confirmation)
	end

	def delete

	end
end

projeto/app/helpers/alunos_helper.rb
module AlunosHelper
end

projeto/app/helpers/application_helper.rb
module ApplicationHelper
	def error_tag(model, attribute)
		if model.errors.has_key? attribute
			content_tag :div, model.errors[attribute].first,
			:class => 'error_message'
		end
	end
end

projeto/app/views/alunos/_form.html.erb
<%= form_for(@aluno) do |f| %>
  <% if @aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% @aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ra %><br>
    <%= f.text_field :ra %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :curso %><br>
    <%= f.text_field :curso %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

projeto/app/views/alunos/edit.html.erb
<h1>Editing Aluno</h1>

<%= render 'form' %>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Back', alunos_path %>

projeto/app/views/alunos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Alunos</h1>

<table>
  <thead>
    <tr>
      <th>Ra</th>
      <th>Nome</th>
      <th>Curso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.ra %></td>
        <td><%= aluno.nome %></td>
        <td><%= aluno.curso %></td>
        <td><%= link_to 'Show', aluno %></td>
        <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Destroy', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aluno', new_aluno_path %>

projeto/app/views/alunos/new.html.erb
<h1>New Aluno</h1>

<%= render 'form' %>

<%= link_to 'Back', alunos_path %>

projeto/app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ra:</strong>
  <%= @aluno.ra %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @aluno.curso %>
</p>

<%= link_to 'Edit', edit_aluno_path(@aluno) %> |
<%= link_to 'Back', alunos_path %>

projeto/app/views/home/index.html.erb
<h1>Bem vindo ao site de Registro de Alunos</h1>

<h2>Alunos recem cadastrados</h2>

<ul>
	<% @alunos.each do |aluno| %>
		<li><%= link_to aluno.nome_completo, aluno%></li>
		
	<%end %>
</ul>

projeto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projeto</title>
  <link rel="stylesheet" type="text/css" href="href='http://fonts.googleapis.com/css?family=Pacifico'"/>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  

</head>
<body>
	<header>
		<div id="header">
			<h1><%= link_to "Projeto", root_path%></h1>
			<nav>
				<ul>
					<li><%= link_to "Alunos",alunos_path
					%></li>
					<li><%= link_to "Cadastro",new_user_path%></li>
				</ul>
			</nav>
		</div>
	</header>

<div id="content">
	<% if notice.present? %>
		<p id="notice"><%= notice %> </p>
	<% end %>
	
	<% if alert.present? %>
		<p id="alert"><%= alert %> </p>
	<% end %>

	<%= yield %>
</div>

</body>
</html>

projeto/app/views/users/_form.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<h2>Informe corretamente os dados solicitados</h2>
	</div>
<% end %>

<%= form_for @user do |f| %>
	<p>
		<%= f.label :nome %> 
		<%= f.text_field :nome %>
		<%= error_tag @user, :nome %>
	</p>
	<p>
		<%= f.label :email %> 
		<%= f.text_field :email %>
		<%= error_tag @user, :email %>
	</p>
	<p>
		<%= f.label :password %>
		<%= f.password_field :password %>
		<%= error_tag @user, :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %> 
		<%= f.password_field :password_confirmation %>
		<%= error_tag @user, :password_confirmation %>
	</p>
	<p>
		<%= f.submit %>
	</p>

<% end%>

projeto/app/views/users/edit.html.erb
<h1>Editando Usuario</h1>

<%= render 'form'%>

<%= link_to "Voltar", @user%>

projeto/app/views/users/new.html.erb
<h1>Cadastro de Usuarios</h1>

<%= render 'form'%>

<%= link_to "Voltar", @user %>

projeto/app/views/users/show.html.erb
<h1>Usuario: <%= @user.nome%></h1>


<p>Email: <%= @user.email%></p>

<%= link_to 'Editar Perfil', edit_user_path(@user)%>